-- @C:\Users\User\Documents\mr_diy_drop_tables.sql
-- ==========================================
-- DROP ALL TABLES FOR MR. DIY DATABASE
-- ==========================================


-- ========== Drop all 21 entities ==========
DROP TABLE Product CASCADE CONSTRAINTS;
DROP TABLE Person CASCADE CONSTRAINTS;
DROP TABLE Warehouse CASCADE CONSTRAINTS;
DROP TABLE LoyaltyProgram CASCADE CONSTRAINTS;
DROP TABLE Employee CASCADE CONSTRAINTS;
DROP TABLE Customer CASCADE CONSTRAINTS;
DROP TABLE Supplier CASCADE CONSTRAINTS;
DROP TABLE Branch CASCADE CONSTRAINTS;
DROP TABLE Maintenance CASCADE CONSTRAINTS;
DROP TABLE Training CASCADE CONSTRAINTS;
DROP TABLE ITSystem CASCADE CONSTRAINTS;
DROP TABLE Inventory CASCADE CONSTRAINTS;
DROP TABLE Procurement CASCADE CONSTRAINTS;
DROP TABLE Promotion CASCADE CONSTRAINTS;
DROP TABLE SalesTransaction CASCADE CONSTRAINTS;
DROP TABLE Payment CASCADE CONSTRAINTS;
DROP TABLE Delivery CASCADE CONSTRAINTS;
DROP TABLE Complaint CASCADE CONSTRAINTS;
DROP TABLE ProductReturn CASCADE CONSTRAINTS;
DROP TABLE Review CASCADE CONSTRAINTS;
DROP TABLE AuditActivity CASCADE CONSTRAINTS;

-- ========== Drop all explosion tables ==========
DROP TABLE PersonReviewSubmission CASCADE CONSTRAINTS;
DROP TABLE PersonBranchInteraction CASCADE CONSTRAINTS;
DROP TABLE PersonComplaintRecord CASCADE CONSTRAINTS;
DROP TABLE PersonProductInteraction CASCADE CONSTRAINTS;
DROP TABLE PersonPaymentTransaction CASCADE CONSTRAINTS;
DROP TABLE PersonProductReturnRequest CASCADE CONSTRAINTS;
DROP TABLE PersonDeliveryRecord CASCADE CONSTRAINTS;
DROP TABLE CustomerPromotionRedemption CASCADE CONSTRAINTS;
DROP TABLE CustomerSalesTransaction CASCADE CONSTRAINTS;
DROP TABLE EmployeeCustomerSupport CASCADE CONSTRAINTS;
DROP TABLE EmployeeITSystemAccess CASCADE CONSTRAINTS;
DROP TABLE EmployeeTrainingEnrollment CASCADE CONSTRAINTS;
DROP TABLE EmployeeInventoryHandling CASCADE CONSTRAINTS;
DROP TABLE EmployeeMaintenanceAssignment CASCADE CONSTRAINTS;
DROP TABLE EmployeeWarehouseAssignment CASCADE CONSTRAINTS;
DROP TABLE SupplierAuditInspection CASCADE CONSTRAINTS;
DROP TABLE SupplierInventorySupply CASCADE CONSTRAINTS;
DROP TABLE BranchProductStock CASCADE CONSTRAINTS;
DROP TABLE BranchPromotionAvailability CASCADE CONSTRAINTS;
DROP TABLE ProductSalesTransactionDetail CASCADE CONSTRAINTS;
DROP TABLE ProductAuditCheck CASCADE CONSTRAINTS;
DROP TABLE ProductProcurementRequest CASCADE CONSTRAINTS;
DROP TABLE ProductDeliveryShipment CASCADE CONSTRAINTS;
DROP TABLE ProductComplaintReport CASCADE CONSTRAINTS;
DROP TABLE PromotionProductLink CASCADE CONSTRAINTS;
DROP TABLE ProductReturnInventoryUpdate CASCADE CONSTRAINTS;
DROP TABLE ProductReturnProductDetail CASCADE CONSTRAINTS;
DROP TABLE ComplaintMaintenanceAction CASCADE CONSTRAINTS;
DROP TABLE ComplaintReviewFeedback CASCADE CONSTRAINTS;
DROP TABLE ComplaintTrainingResponse CASCADE CONSTRAINTS;
DROP TABLE DeliveryInventoryContents CASCADE CONSTRAINTS;
DROP TABLE ProcurementInventoryRequest CASCADE CONSTRAINTS;
DROP TABLE ProcurementWarehouse CASCADE CONSTRAINTS;
DROP TABLE AuditComplaintInspection CASCADE CONSTRAINTS;
DROP TABLE AuditInventoryCheck CASCADE CONSTRAINTS;
DROP TABLE AuditTrainingAssessment CASCADE CONSTRAINTS;
DROP TABLE AuditITSystemEvaluation CASCADE CONSTRAINTS;
DROP TABLE AuditLoyaltyProgramCompliance CASCADE CONSTRAINTS;
DROP TABLE AuditMaintenanceFollowUp CASCADE CONSTRAINTS;
DROP TABLE WarehouseProductStock CASCADE CONSTRAINTS;
DROP TABLE WarehouseTrainingSession CASCADE CONSTRAINTS;
DROP TABLE WarehouseMaintenanceRecord CASCADE CONSTRAINTS;
DROP TABLE MaintenanceITSystemService CASCADE CONSTRAINTS;
DROP TABLE ITSystemLoyaltyProgram CASCADE CONSTRAINTS;
